#!/bin/bash

# If the configmaker submodule is staged for commit
if [[ $(git diff --name-only --staged | grep -nwq "^configMaker$") ]]; then
  cd configMaker

  config_maker_branch="$(git rev-parse --abbrev-ref HEAD)"

  if [[ $config_maker_branch != "master" ]];then
    echo ""
    echo "ERROR: submodule configMaker must be on the master branch"
    echo "  configMaker was instead on branch: $config_maker_branch"
    echo ""
    echo "Aborting commit"
    exit 1
  fi
fi
