#!/bin/bash

cd configMaker

config_maker_branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ $config_maker_branch != "master" ]];then
  echo ""
  echo "ERROR: submodule configMaker must be on the master branch"
  echo "  configMaker was instead on branch: $config_maker_branch"
  echo ""
  echo "Aborting commit"
  exit 1
fi

