#!/bin/bash

#changed_files=($(git diff --name-only HEAD HEAD~1))

# For Testing
changed_files=("js/vue.min.js" "css/theme.css" "materialize/css/materialize.min.css" "configMaker" "css/nojs.css")

# Checks if a string contains a substring from an array
#   @param   string  The string to examine for substrings
#   @param   array   The array of substrings
#   @outputs string "true" if an element of $2 was found to be a substring of $1 "false" otherwise
#   @return  1 on missing param 0 on success
matches_list () {
  if [ -z "$1" ];then
    echo "missing param string to be checked"
    return 1
  fi

  if [ -z "$2" ];then
    echo "missing param array of substrings"
    return 1
  fi

  substrings=("$@")

  for substring in "${substrings[@]}"; do
    if [[ $1 == *"$substring"* ]]; then
      echo true
      return 0
    fi
  done

  echo false
  return 0
}

if ! test=$(matches_list "js/vue.min.js" "${changed_files[@]}"); then
  echo "ERROR: $test"
fi

echo $test

cd configMaker

git checkout standalone

for file in "${changed_files[@]}"; do
  if [[ $file == *"materialize"* || $file == *"vue"* || $file == *"configMaker"* && $file != "configMaker" ]]; then
#    cp "../$file" $file
    echo "Copied $file to configMaker/$file"
  elif [[ $file == *"nojs"* || $file == *"shared"* || $file == *"theme"* ]]; then
    echo "Warning changed shared file $file"
  else
    echo $file
  fi
done

exit 0
